# https://github.com/mergeability/mergeable

defaults:
  checks_failure_payload: &checks_failure_payload
    title: 'Mergeable Run have been Completed!'
    summary: '### Status: {{toUpperCase validationStatus}}
              Here are some stats of the run:
              {{validationCount}} validations were ran.
              {{passCount}} PASSED
              {{failCount}} FAILED'
    text: '{{#each validationSuites}}\n
          #### {{{statusIcon status}}} Validator: {{toUpperCase name}}\n
          {{#each validations }} * {{{statusIcon status}}} ***{{{ description }}}***\n
                  Input : {{{details.input}}}\n
                  Settings : {{{displaySettings details.settings}}}\n
                  {{/each}}\n
          {{/each}}'

version: 2
mergeable:
  - when: pull_request.*, pull_request_review.*
    name: 'Validate Pull Request Description'
    validate:
      - do: description
        no_empty:
          enabled: true
    fail:
      - do: checks
        status: 'failure'
        payload: *checks_failure_payload
      - do: comment
        payload:
          body: 'Description is necessary and should not be empty. Kindly provide details with **what** was changed, **why** it was changed, and **how** it was changed.'
  - when: pull_request.*, pull_request_review.*
    name: 'Validate Pull Request Title'
    validate:
      - do: title
        no_empty:
          enabled: true
    fail:
      - do: checks
        status: 'failure'
        payload: *checks_failure_payload
      - do: comment
        payload:
          body: 'Title is necessary and should not be empty.'
  - when: pull_request.*, pull_request_review.*
    name: 'Validate Pull Request Size'
    validate:
      - do: size
        ignore: 
          - '*.lock'
          - '*-lock.json'
        lines:
          max:
            count: 500
    fail:
      - do: checks
        status: 'failure'
        payload: *checks_failure_payload
      - do: comment
        payload: 
          body: 'Lines of code have too many changes. It should be under 500 lines of addtions and deletions.'
  - when: pull_request.*, pull_request_review.*
    name: 'Validate Pull Request has one or more assignees'
    validate:
      - do: assignee
        min:
          count: 1
    fail:
      - do: checks
        status: 'failure'
        payload: *checks_failure_payload
      - do: assign
        assignees: [ '@author' ]
  - when: pull_request.*, pull_request_review.*
    name: 'Ensure Pull Request has been approved'
    validate:
      - do: approvals
        min:
          count: 1
    pass:
      - do: labels
        labels: [ 'work in progress' ]
        mode: 'delete'
      - do: labels
        labels: [ 'ready for merging' ]
        mode: 'add'
    fail:
      - do: request_review
        reviewers: [ 'tenshiAMD' ]
  - when: pull_request.*, pull_request_review.*
    name: 'Restrict Pull Request as Work in Progress'
    validate:
      - do: label
        must_exclude:
          regex: 'work in progress'
  - when: pull_request.opened, pull_request.reopened
    name: 'Set labels for Pull Request'
    validate:
      - do: label
        no_empty:
          enabled: true
    pass:
      - do: labels
        labels: [ 'work in progress' ]
        mode: 'add'
    fail:
      - do: labels
        labels: [ 'work in progress' ]
        mode: 'add'
